name: biznis
description: Expense tracking application.
publish_to: "none"

version: 1.2.0+27

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_toggle_switch: ^0.7.0
  devicelocale: ^0.7.0
  # appwrite: ^8.1.0 # disabled for now, considering firebase instead
  dio: ^5.0.1
  file_picker: ^5.2.2
  fimber: ^0.7.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.14.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_floating_bottom_bar: ^1.1.0
  flutter_iconpicker: ^3.2.4
  flutter_keyboard_visibility: ^5.4.1
  flutter_move_task_back: ^1.0.0
  font_awesome_flutter: ^10.5.0
  fuzzywuzzy: ^1.1.6
  get_it: ^7.6.0
  get_storage: ^2.1.1
  go_router: ^10.0.0
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  list_ext: ^1.0.6
  math_parser: ^1.5.1
  multiple_result: ^5.1.0
  package_info_plus: ^4.1.0
  path_provider: ^2.0.15  
  restart_app: ^1.2.1
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  simple_animations: ^5.0.2
  sliver_app_bar_builder: ^1.1.0
  sprintf: ^7.0.0
  uuid: ^3.0.7
  version: ^3.0.2
  wakelock_plus: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: any
  flutter_lints: ^2.0.0
  flutter_rename_app_plus3: ^1.2.1
  flutter_test:
    sdk: flutter
  go_router_builder: any
  isar_generator: ^3.1.0+1

flutter_rename_app_plus:
  application_name: Budget Compass
  ios_bundle_name: Budget Compass

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/lang/
